import raynor from '../assets/listCard/img1.png'
import raynor1 from '../assets/listCard/img2.png'
import raynor2 from '../assets/listCard/img3.png'
import raynor3 from '../assets/listCard/img4.png'
import raynor4 from '../assets/listCard/img5.png'
import raynor5 from '../assets/listCard/img6.png'
import raynor6 from '../assets/listCard/img7.png'
import raynor7 from '../assets/listCard/img8.png'
import raynor8 from '../assets/listCard/img9.png'
import raynor9 from '../assets/listCard/img10.png'


export const cardListData =[
{
	id:1,
	title: "Nursing Assistant",
	img: raynor,
	comp: "Raynor Group",
},
{
	id:2,
	title:'Marketing Coordinator',
	img: raynor2,
	comp: 'Hegmann, Kreiger and Bayer',
},
	{
		id: 3,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	}, 
	{
		id: 4,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 5,
		title: "Nursing Assistant",
		img: raynor5,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{ 
		id: 6,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 7,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 8,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 9,
		title: 'Nursing Assistant',
		img: raynor9,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 10,
		title: "Medical Assistant",
		img: raynor1,
		comp: "Dare - Treutel",
	},
	{
		id: 141,
		title: 'Dog Trainer',
		img: raynor7,
		comp: 'Goyette and Sons',
	},
	{
		id: 11,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Padberg - Bailey',
	},
	{
		id: 12,
		title: "Nursing Assistant",
		img: raynor,
		comp: "Raynor Group",
	},
	{
		id: 13,
		title: 'Marketing Coordinator',
		img: raynor6,
		comp: 'Hegmann, Kreiger and Bayer',
	},
	{
		id: 14,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 15,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 16,
		title: "Nursing Assistant",
		img: raynor5,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{
		id: 17,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 18,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 19,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 20,
		title: 'Nursing Assistant',
		img: raynor6,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 21,
		title: "Medical Assistant",
		img: raynor6,
		comp: "Dare - Treutel",
	},
	{
		id: 22,
		title: 'Dog Trainer',
		img: raynor7,
		comp: 'Goyette and Sons',
	},
	{
		id: 23,
		title: 'Dog Trainer',
		img: raynor6,
		comp: 'Padberg - Bailey',
	},
	{
		id: 24,
		title: "Nursing Assistant",
		img: raynor,
		comp: "Raynor Group",
	},
	{
		id: 25,
		title: 'Marketing Coordinator',
		img: raynor2,
		comp: 'Hegmann, Kreiger and Bayer',
	},
	{
		id: 26,
		title: "Web Designer",
		img: raynor6,
		comp: "Dare - Treutel",
	},
	{
		id: 27,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 28,
		title: "Nursing Assistant",
		img: raynor6,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{
		id: 29,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 30,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 31,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 32,
		title: 'Nursing Assistant',
		img: raynor9,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 33,
		title: "Medical Assistant",
		img: raynor1,
		comp: "Dare - Treutel",
	},
	{
		id: 34,
		title: 'Dog Trainer',
		img: raynor7,
		comp: 'Goyette and Sons',
	},
	{
		id: 35,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Padberg - Bailey',
	},
	{
		id: 36,
		title: "Nursing Assistant",
		img: raynor,
		comp: "Raynor Group",
	},
	{
		id: 37,
		title: 'Marketing Coordinator',
		img: raynor2,
		comp: 'Hegmann, Kreiger and Bayer',
	},
	{
		id: 38,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 39,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 40,
		title: "Nursing Assistant",
		img: raynor5,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{
		id: 41,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 42,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 43,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 44,
		title: 'Nursing Assistant',
		img: raynor9,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 45,
		title: "Medical Assistant",
		img: raynor1,
		comp: "Dare - Treutel",
	},
	{
		id: 46,
		title: 'Dog Trainer',
		img: raynor7,
		comp: 'Goyette and Sons',
	},
	{
		id: 47,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Padberg - Bailey',
	},
	{
		id: 48,
		title: "Nursing Assistant",
		img: raynor,
		comp: "Raynor Group",
	},
	{
		id: 49,
		title: 'Marketing Coordinator',
		img: raynor2,
		comp: 'Hegmann, Kreiger and Bayer',
	},
	{
		id: 50,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 51,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 52,
		title: "Nursing Assistant",
		img: raynor5,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{
		id: 53,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 54,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 55,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 56,
		title: 'Nursing Assistant',
		img: raynor9,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 57,
		title: "Medical Assistant",
		img: raynor1,
		comp: "Dare - Treutel",
	},
	{
		id: 58,
		title: 'Dog Trainer',
		img: raynor7,
		comp: 'Goyette and Sons',
	},
	{
		id: 59,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Padberg - Bailey',
	},
	{
		id: 60,
		title: "Nursing Assistant",
		img: raynor,
		comp: "Raynor Group",
	},
	{
		id: 62,
		title: 'Marketing Coordinator',
		img: raynor2,
		comp: 'Hegmann, Kreiger and Bayer',
	},
	{
		id: 63,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 64,
		title: 'President of Sales',
		img: raynor4,
		comp: 'Feest Group',
	},
	{
		id: 65,
		title: "Nursing Assistant",
		img: raynor5,
		comp: "Altenwerth, Medhurst and Roberts",
	},
	{
		id: 66,
		title: 'President of Sales',
		img: raynor2,
		comp: 'Grimes Inc',
	},
	{
		id: 67,
		title: "Web Designer",
		img: raynor3,
		comp: "Dare - Treutel",
	},
	{
		id: 68,
		title: 'Dog Trainer',
		img: raynor4,
		comp: 'Goyette and Sons',
	},
	{
		id: 69,
		title: 'Nursing Assistant',
		img: raynor9,
		comp: 'Rempel, Hand and Herzog',
	},
	{
		id: 160,
		title: "Medical Assistant",
		img: raynor8,
		comp: "Dare - Treutel",
	},
	{
		id: 116,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Goyette and Sons',
	},
	{
		id: 118,
		title: 'Dog Trainer',
		img: raynor8,
		comp: 'Padberg - Bailey',
	},
] 